// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgsAdoikJDbG0aTzJWRDda-ewAXxeoqoU',
    appId: '1:1034594274722:web:17c9743dc0d62af35ab6fb',
    messagingSenderId: '1034594274722',
    projectId: 'hero-games-case',
    authDomain: 'hero-games-case.firebaseapp.com',
    storageBucket: 'hero-games-case.appspot.com',
    measurementId: 'G-J6FCQYDNQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSte7QW3u3xs9H9HHbna0Fbcsv_zRPr60',
    appId: '1:1034594274722:android:2a582ec7fec24a7a5ab6fb',
    messagingSenderId: '1034594274722',
    projectId: 'hero-games-case',
    storageBucket: 'hero-games-case.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKyN7BxlKjDsyrd4xk0w241TMzYT1nBmE',
    appId: '1:1034594274722:ios:7e2831c0096548d55ab6fb',
    messagingSenderId: '1034594274722',
    projectId: 'hero-games-case',
    storageBucket: 'hero-games-case.appspot.com',
    iosBundleId: 'com.example.heroGames',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKyN7BxlKjDsyrd4xk0w241TMzYT1nBmE',
    appId: '1:1034594274722:ios:2657689a52c602fb5ab6fb',
    messagingSenderId: '1034594274722',
    projectId: 'hero-games-case',
    storageBucket: 'hero-games-case.appspot.com',
    iosBundleId: 'com.example.heroGames.RunnerTests',
  );
}
